executable = condor/Combined/MHc-130_MA-90_vs_ttZ_FA0BCE/run.sh
jobbatchname = ParticeNet_MHc-130_MA-90_vs_ttZ_Combined
+singularityimage = "/data9/Users/choij/Singularity/images/cuda11.8"
requirements = HasSingularity
request_disk = 100 GB
request_memory = 100 GB
request_cpus = 20
request_gpus = 1
log = condor/Combined/MHc-130_MA-90_vs_ttZ_FA0BCE/job.log
output = condor/Combined/MHc-130_MA-90_vs_ttZ_FA0BCE/job.out
error = condor/Combined/MHc-130_MA-90_vs_ttZ_FA0BCE/job.err
queue 1